# SET CONTROL PLANE IP AND PORT
apiVersion: kubeadm.k8s.io/v1beta2
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: ${NODE_JOIN_TOKEN}
  ttl: 720h #Token will never expire TODO
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: ${NODE_HOST_IP}
  bindPort: 6443
certificateKey: ${MASTER_CERTIFICATE_KEY}
nodeRegistration:
  name: ${NODE_NAME}
  criSocket: unix:///run/containerd/containerd.sock
  kubeletExtraArgs:
    cgroup-driver: "systemd"
  ${TAINT_MASTER_YAML}
