apiVersion: kubeadm.k8s.io/v1beta2
caCertPath: /etc/kubernetes/pki/ca.crt
discovery:
  bootstrapToken:
    apiServerEndpoint: kube-apiserver:6443
    token: ${NODE_JOIN_TOKEN}
    unsafeSkipCAVerification: true # Remove when we handle certificates TODO
kind: JoinConfiguration
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock
${CONTROL_PLANE_REGISTRATION}
